#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Transporte_Trome
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="BDTrome")]
	public partial class TromeDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Definiciones de métodos de extensibilidad
    partial void OnCreated();
    partial void InsertCarritoCompras(CarritoCompras instance);
    partial void UpdateCarritoCompras(CarritoCompras instance);
    partial void DeleteCarritoCompras(CarritoCompras instance);
    partial void InsertColaboradorEnvio(ColaboradorEnvio instance);
    partial void UpdateColaboradorEnvio(ColaboradorEnvio instance);
    partial void DeleteColaboradorEnvio(ColaboradorEnvio instance);
    partial void InsertCliente(Cliente instance);
    partial void UpdateCliente(Cliente instance);
    partial void DeleteCliente(Cliente instance);
    partial void InsertColaborador(Colaborador instance);
    partial void UpdateColaborador(Colaborador instance);
    partial void DeleteColaborador(Colaborador instance);
    partial void InsertEnvio(Envio instance);
    partial void UpdateEnvio(Envio instance);
    partial void DeleteEnvio(Envio instance);
    partial void InsertServicio(Servicio instance);
    partial void UpdateServicio(Servicio instance);
    partial void DeleteServicio(Servicio instance);
    partial void InsertUsuario(Usuario instance);
    partial void UpdateUsuario(Usuario instance);
    partial void DeleteUsuario(Usuario instance);
    partial void InsertVehiculo(Vehiculo instance);
    partial void UpdateVehiculo(Vehiculo instance);
    partial void DeleteVehiculo(Vehiculo instance);
    #endregion
		
		public TromeDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["BDTromeConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public TromeDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public TromeDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public TromeDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public TromeDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<CarritoCompras> CarritoCompras
		{
			get
			{
				return this.GetTable<CarritoCompras>();
			}
		}
		
		public System.Data.Linq.Table<ColaboradorEnvio> ColaboradorEnvio
		{
			get
			{
				return this.GetTable<ColaboradorEnvio>();
			}
		}
		
		public System.Data.Linq.Table<Cliente> Cliente
		{
			get
			{
				return this.GetTable<Cliente>();
			}
		}
		
		public System.Data.Linq.Table<Colaborador> Colaborador
		{
			get
			{
				return this.GetTable<Colaborador>();
			}
		}
		
		public System.Data.Linq.Table<Envio> Envio
		{
			get
			{
				return this.GetTable<Envio>();
			}
		}
		
		public System.Data.Linq.Table<Servicio> Servicio
		{
			get
			{
				return this.GetTable<Servicio>();
			}
		}
		
		public System.Data.Linq.Table<Usuario> Usuario
		{
			get
			{
				return this.GetTable<Usuario>();
			}
		}
		
		public System.Data.Linq.Table<Vehiculo> Vehiculo
		{
			get
			{
				return this.GetTable<Vehiculo>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.CarritoCompras")]
	public partial class CarritoCompras : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _IdCarrito;
		
		private int _IdCliente;
		
		private int _IdServicio;
		
		private int _Cantidad;
		
		private System.Nullable<decimal> _Subtotal;
		
		private System.Nullable<decimal> _IGV;
		
		private System.Nullable<decimal> _Total;
		
		private EntityRef<Cliente> _Cliente;
		
		private EntityRef<Servicio> _Servicio;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdCarritoChanging(int value);
    partial void OnIdCarritoChanged();
    partial void OnIdClienteChanging(int value);
    partial void OnIdClienteChanged();
    partial void OnIdServicioChanging(int value);
    partial void OnIdServicioChanged();
    partial void OnCantidadChanging(int value);
    partial void OnCantidadChanged();
    partial void OnSubtotalChanging(System.Nullable<decimal> value);
    partial void OnSubtotalChanged();
    partial void OnIGVChanging(System.Nullable<decimal> value);
    partial void OnIGVChanged();
    partial void OnTotalChanging(System.Nullable<decimal> value);
    partial void OnTotalChanged();
    #endregion
		
		public CarritoCompras()
		{
			this._Cliente = default(EntityRef<Cliente>);
			this._Servicio = default(EntityRef<Servicio>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdCarrito", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int IdCarrito
		{
			get
			{
				return this._IdCarrito;
			}
			set
			{
				if ((this._IdCarrito != value))
				{
					this.OnIdCarritoChanging(value);
					this.SendPropertyChanging();
					this._IdCarrito = value;
					this.SendPropertyChanged("IdCarrito");
					this.OnIdCarritoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdCliente", DbType="Int NOT NULL")]
		public int IdCliente
		{
			get
			{
				return this._IdCliente;
			}
			set
			{
				if ((this._IdCliente != value))
				{
					if (this._Cliente.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIdClienteChanging(value);
					this.SendPropertyChanging();
					this._IdCliente = value;
					this.SendPropertyChanged("IdCliente");
					this.OnIdClienteChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdServicio", DbType="Int NOT NULL")]
		public int IdServicio
		{
			get
			{
				return this._IdServicio;
			}
			set
			{
				if ((this._IdServicio != value))
				{
					if (this._Servicio.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIdServicioChanging(value);
					this.SendPropertyChanging();
					this._IdServicio = value;
					this.SendPropertyChanged("IdServicio");
					this.OnIdServicioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cantidad", DbType="Int NOT NULL")]
		public int Cantidad
		{
			get
			{
				return this._Cantidad;
			}
			set
			{
				if ((this._Cantidad != value))
				{
					this.OnCantidadChanging(value);
					this.SendPropertyChanging();
					this._Cantidad = value;
					this.SendPropertyChanged("Cantidad");
					this.OnCantidadChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Subtotal", DbType="Decimal(10,2)")]
		public System.Nullable<decimal> Subtotal
		{
			get
			{
				return this._Subtotal;
			}
			set
			{
				if ((this._Subtotal != value))
				{
					this.OnSubtotalChanging(value);
					this.SendPropertyChanging();
					this._Subtotal = value;
					this.SendPropertyChanged("Subtotal");
					this.OnSubtotalChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IGV", AutoSync=AutoSync.Always, DbType="Decimal(13,4)", IsDbGenerated=true, UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<decimal> IGV
		{
			get
			{
				return this._IGV;
			}
			set
			{
				if ((this._IGV != value))
				{
					this.OnIGVChanging(value);
					this.SendPropertyChanging();
					this._IGV = value;
					this.SendPropertyChanged("IGV");
					this.OnIGVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Total", AutoSync=AutoSync.Always, DbType="Decimal(14,4)", IsDbGenerated=true, UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<decimal> Total
		{
			get
			{
				return this._Total;
			}
			set
			{
				if ((this._Total != value))
				{
					this.OnTotalChanging(value);
					this.SendPropertyChanging();
					this._Total = value;
					this.SendPropertyChanged("Total");
					this.OnTotalChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TCliente_CarritoCompras", Storage="_Cliente", ThisKey="IdCliente", OtherKey="IdCliente", IsForeignKey=true)]
		public Cliente Cliente
		{
			get
			{
				return this._Cliente.Entity;
			}
			set
			{
				Cliente previousValue = this._Cliente.Entity;
				if (((previousValue != value) 
							|| (this._Cliente.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Cliente.Entity = null;
						previousValue.CarritoCompras.Remove(this);
					}
					this._Cliente.Entity = value;
					if ((value != null))
					{
						value.CarritoCompras.Add(this);
						this._IdCliente = value.IdCliente;
					}
					else
					{
						this._IdCliente = default(int);
					}
					this.SendPropertyChanged("Cliente");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TServicio_CarritoCompras", Storage="_Servicio", ThisKey="IdServicio", OtherKey="IdServicio", IsForeignKey=true)]
		public Servicio Servicio
		{
			get
			{
				return this._Servicio.Entity;
			}
			set
			{
				Servicio previousValue = this._Servicio.Entity;
				if (((previousValue != value) 
							|| (this._Servicio.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Servicio.Entity = null;
						previousValue.CarritoCompras.Remove(this);
					}
					this._Servicio.Entity = value;
					if ((value != null))
					{
						value.CarritoCompras.Add(this);
						this._IdServicio = value.IdServicio;
					}
					else
					{
						this._IdServicio = default(int);
					}
					this.SendPropertyChanged("Servicio");
				}
			}
		}

        public int TarifaBase { get; internal set; }
        public object Descripcion { get; internal set; }

        public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ColaboradorEnvio")]
	public partial class ColaboradorEnvio : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _IdColaborador;
		
		private int _IdEnvio;
		
		private EntityRef<Colaborador> _Colaborador;
		
		private EntityRef<Envio> _Envio;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdColaboradorChanging(int value);
    partial void OnIdColaboradorChanged();
    partial void OnIdEnvioChanging(int value);
    partial void OnIdEnvioChanged();
    #endregion
		
		public ColaboradorEnvio()
		{
			this._Colaborador = default(EntityRef<Colaborador>);
			this._Envio = default(EntityRef<Envio>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdColaborador", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int IdColaborador
		{
			get
			{
				return this._IdColaborador;
			}
			set
			{
				if ((this._IdColaborador != value))
				{
					if (this._Colaborador.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIdColaboradorChanging(value);
					this.SendPropertyChanging();
					this._IdColaborador = value;
					this.SendPropertyChanged("IdColaborador");
					this.OnIdColaboradorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdEnvio", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int IdEnvio
		{
			get
			{
				return this._IdEnvio;
			}
			set
			{
				if ((this._IdEnvio != value))
				{
					if (this._Envio.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIdEnvioChanging(value);
					this.SendPropertyChanging();
					this._IdEnvio = value;
					this.SendPropertyChanged("IdEnvio");
					this.OnIdEnvioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TColaborador_ColaboradorEnvio", Storage="_Colaborador", ThisKey="IdColaborador", OtherKey="IdColaborador", IsForeignKey=true)]
		public Colaborador Colaborador
		{
			get
			{
				return this._Colaborador.Entity;
			}
			set
			{
				Colaborador previousValue = this._Colaborador.Entity;
				if (((previousValue != value) 
							|| (this._Colaborador.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Colaborador.Entity = null;
						previousValue.ColaboradorEnvio.Remove(this);
					}
					this._Colaborador.Entity = value;
					if ((value != null))
					{
						value.ColaboradorEnvio.Add(this);
						this._IdColaborador = value.IdColaborador;
					}
					else
					{
						this._IdColaborador = default(int);
					}
					this.SendPropertyChanged("Colaborador");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TEnvio_ColaboradorEnvio", Storage="_Envio", ThisKey="IdEnvio", OtherKey="IdEnvio", IsForeignKey=true)]
		public Envio Envio
		{
			get
			{
				return this._Envio.Entity;
			}
			set
			{
				Envio previousValue = this._Envio.Entity;
				if (((previousValue != value) 
							|| (this._Envio.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Envio.Entity = null;
						previousValue.ColaboradorEnvio.Remove(this);
					}
					this._Envio.Entity = value;
					if ((value != null))
					{
						value.ColaboradorEnvio.Add(this);
						this._IdEnvio = value.IdEnvio;
					}
					else
					{
						this._IdEnvio = default(int);
					}
					this.SendPropertyChanged("Envio");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TCliente")]
	public partial class Cliente : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _IdCliente;
		
		private string _Nombre;
		
		private string _Direccion;
		
		private string _Telefono;
		
		private string _CodUsuario;
		
		private string _Contrasena;
		
		private EntitySet<CarritoCompras> _CarritoCompras;
		
		private EntitySet<Envio> _Envio;
		
		private EntityRef<Usuario> _Usuario;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdClienteChanging(int value);
    partial void OnIdClienteChanged();
    partial void OnNombreChanging(string value);
    partial void OnNombreChanged();
    partial void OnDireccionChanging(string value);
    partial void OnDireccionChanged();
    partial void OnTelefonoChanging(string value);
    partial void OnTelefonoChanged();
    partial void OnCodUsuarioChanging(string value);
    partial void OnCodUsuarioChanged();
    partial void OnContrasenaChanging(string value);
    partial void OnContrasenaChanged();
    #endregion
		
		public Cliente()
		{
			this._CarritoCompras = new EntitySet<CarritoCompras>(new Action<CarritoCompras>(this.attach_CarritoCompras), new Action<CarritoCompras>(this.detach_CarritoCompras));
			this._Envio = new EntitySet<Envio>(new Action<Envio>(this.attach_Envio), new Action<Envio>(this.detach_Envio));
			this._Usuario = default(EntityRef<Usuario>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdCliente", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int IdCliente
		{
			get
			{
				return this._IdCliente;
			}
			set
			{
				if ((this._IdCliente != value))
				{
					this.OnIdClienteChanging(value);
					this.SendPropertyChanging();
					this._IdCliente = value;
					this.SendPropertyChanged("IdCliente");
					this.OnIdClienteChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nombre", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string Nombre
		{
			get
			{
				return this._Nombre;
			}
			set
			{
				if ((this._Nombre != value))
				{
					this.OnNombreChanging(value);
					this.SendPropertyChanging();
					this._Nombre = value;
					this.SendPropertyChanged("Nombre");
					this.OnNombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Direccion", DbType="VarChar(200) NOT NULL", CanBeNull=false)]
		public string Direccion
		{
			get
			{
				return this._Direccion;
			}
			set
			{
				if ((this._Direccion != value))
				{
					this.OnDireccionChanging(value);
					this.SendPropertyChanging();
					this._Direccion = value;
					this.SendPropertyChanged("Direccion");
					this.OnDireccionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Telefono", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string Telefono
		{
			get
			{
				return this._Telefono;
			}
			set
			{
				if ((this._Telefono != value))
				{
					this.OnTelefonoChanging(value);
					this.SendPropertyChanging();
					this._Telefono = value;
					this.SendPropertyChanged("Telefono");
					this.OnTelefonoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CodUsuario", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string CodUsuario
		{
			get
			{
				return this._CodUsuario;
			}
			set
			{
				if ((this._CodUsuario != value))
				{
					if (this._Usuario.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnCodUsuarioChanging(value);
					this.SendPropertyChanging();
					this._CodUsuario = value;
					this.SendPropertyChanged("CodUsuario");
					this.OnCodUsuarioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Contrasena", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Contrasena
		{
			get
			{
				return this._Contrasena;
			}
			set
			{
				if ((this._Contrasena != value))
				{
					this.OnContrasenaChanging(value);
					this.SendPropertyChanging();
					this._Contrasena = value;
					this.SendPropertyChanged("Contrasena");
					this.OnContrasenaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TCliente_CarritoCompras", Storage="_CarritoCompras", ThisKey="IdCliente", OtherKey="IdCliente")]
		public EntitySet<CarritoCompras> CarritoCompras
		{
			get
			{
				return this._CarritoCompras;
			}
			set
			{
				this._CarritoCompras.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TCliente_TEnvio", Storage="_Envio", ThisKey="IdCliente", OtherKey="IdCliente")]
		public EntitySet<Envio> Envio
		{
			get
			{
				return this._Envio;
			}
			set
			{
				this._Envio.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TUsuario_TCliente", Storage="_Usuario", ThisKey="CodUsuario", OtherKey="CodUsuario", IsForeignKey=true)]
		public Usuario Usuario
		{
			get
			{
				return this._Usuario.Entity;
			}
			set
			{
				Usuario previousValue = this._Usuario.Entity;
				if (((previousValue != value) 
							|| (this._Usuario.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Usuario.Entity = null;
						previousValue.Cliente.Remove(this);
					}
					this._Usuario.Entity = value;
					if ((value != null))
					{
						value.Cliente.Add(this);
						this._CodUsuario = value.CodUsuario;
					}
					else
					{
						this._CodUsuario = default(string);
					}
					this.SendPropertyChanged("Usuario");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_CarritoCompras(CarritoCompras entity)
		{
			this.SendPropertyChanging();
			entity.Cliente = this;
		}
		
		private void detach_CarritoCompras(CarritoCompras entity)
		{
			this.SendPropertyChanging();
			entity.Cliente = null;
		}
		
		private void attach_Envio(Envio entity)
		{
			this.SendPropertyChanging();
			entity.Cliente = this;
		}
		
		private void detach_Envio(Envio entity)
		{
			this.SendPropertyChanging();
			entity.Cliente = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TColaborador")]
	public partial class Colaborador : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _IdColaborador;
		
		private string _Nombre;
		
		private string _Cargo;
		
		private string _Telefono;
		
		private string _CodUsuario;
		
		private string _Contrasena;
		
		private System.Nullable<int> _IdVehiculo;
		
		private EntitySet<ColaboradorEnvio> _ColaboradorEnvio;
		
		private EntityRef<Usuario> _Usuario;
		
		private EntityRef<Vehiculo> _Vehiculo;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdColaboradorChanging(int value);
    partial void OnIdColaboradorChanged();
    partial void OnNombreChanging(string value);
    partial void OnNombreChanged();
    partial void OnCargoChanging(string value);
    partial void OnCargoChanged();
    partial void OnTelefonoChanging(string value);
    partial void OnTelefonoChanged();
    partial void OnCodUsuarioChanging(string value);
    partial void OnCodUsuarioChanged();
    partial void OnContrasenaChanging(string value);
    partial void OnContrasenaChanged();
    partial void OnIdVehiculoChanging(System.Nullable<int> value);
    partial void OnIdVehiculoChanged();
    #endregion
		
		public Colaborador()
		{
			this._ColaboradorEnvio = new EntitySet<ColaboradorEnvio>(new Action<ColaboradorEnvio>(this.attach_ColaboradorEnvio), new Action<ColaboradorEnvio>(this.detach_ColaboradorEnvio));
			this._Usuario = default(EntityRef<Usuario>);
			this._Vehiculo = default(EntityRef<Vehiculo>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdColaborador", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int IdColaborador
		{
			get
			{
				return this._IdColaborador;
			}
			set
			{
				if ((this._IdColaborador != value))
				{
					this.OnIdColaboradorChanging(value);
					this.SendPropertyChanging();
					this._IdColaborador = value;
					this.SendPropertyChanged("IdColaborador");
					this.OnIdColaboradorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nombre", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string Nombre
		{
			get
			{
				return this._Nombre;
			}
			set
			{
				if ((this._Nombre != value))
				{
					this.OnNombreChanging(value);
					this.SendPropertyChanging();
					this._Nombre = value;
					this.SendPropertyChanged("Nombre");
					this.OnNombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cargo", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string Cargo
		{
			get
			{
				return this._Cargo;
			}
			set
			{
				if ((this._Cargo != value))
				{
					this.OnCargoChanging(value);
					this.SendPropertyChanging();
					this._Cargo = value;
					this.SendPropertyChanged("Cargo");
					this.OnCargoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Telefono", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string Telefono
		{
			get
			{
				return this._Telefono;
			}
			set
			{
				if ((this._Telefono != value))
				{
					this.OnTelefonoChanging(value);
					this.SendPropertyChanging();
					this._Telefono = value;
					this.SendPropertyChanged("Telefono");
					this.OnTelefonoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CodUsuario", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string CodUsuario
		{
			get
			{
				return this._CodUsuario;
			}
			set
			{
				if ((this._CodUsuario != value))
				{
					if (this._Usuario.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnCodUsuarioChanging(value);
					this.SendPropertyChanging();
					this._CodUsuario = value;
					this.SendPropertyChanged("CodUsuario");
					this.OnCodUsuarioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Contrasena", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Contrasena
		{
			get
			{
				return this._Contrasena;
			}
			set
			{
				if ((this._Contrasena != value))
				{
					this.OnContrasenaChanging(value);
					this.SendPropertyChanging();
					this._Contrasena = value;
					this.SendPropertyChanged("Contrasena");
					this.OnContrasenaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdVehiculo", DbType="Int")]
		public System.Nullable<int> IdVehiculo
		{
			get
			{
				return this._IdVehiculo;
			}
			set
			{
				if ((this._IdVehiculo != value))
				{
					if (this._Vehiculo.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIdVehiculoChanging(value);
					this.SendPropertyChanging();
					this._IdVehiculo = value;
					this.SendPropertyChanged("IdVehiculo");
					this.OnIdVehiculoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TColaborador_ColaboradorEnvio", Storage="_ColaboradorEnvio", ThisKey="IdColaborador", OtherKey="IdColaborador")]
		public EntitySet<ColaboradorEnvio> ColaboradorEnvio
		{
			get
			{
				return this._ColaboradorEnvio;
			}
			set
			{
				this._ColaboradorEnvio.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TUsuario_TColaborador", Storage="_Usuario", ThisKey="CodUsuario", OtherKey="CodUsuario", IsForeignKey=true)]
		public Usuario Usuario
		{
			get
			{
				return this._Usuario.Entity;
			}
			set
			{
				Usuario previousValue = this._Usuario.Entity;
				if (((previousValue != value) 
							|| (this._Usuario.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Usuario.Entity = null;
						previousValue.Colaborador.Remove(this);
					}
					this._Usuario.Entity = value;
					if ((value != null))
					{
						value.Colaborador.Add(this);
						this._CodUsuario = value.CodUsuario;
					}
					else
					{
						this._CodUsuario = default(string);
					}
					this.SendPropertyChanged("Usuario");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TVehiculo_TColaborador", Storage="_Vehiculo", ThisKey="IdVehiculo", OtherKey="IdVehiculo", IsForeignKey=true)]
		public Vehiculo Vehiculo
		{
			get
			{
				return this._Vehiculo.Entity;
			}
			set
			{
				Vehiculo previousValue = this._Vehiculo.Entity;
				if (((previousValue != value) 
							|| (this._Vehiculo.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Vehiculo.Entity = null;
						previousValue.Colaborador.Remove(this);
					}
					this._Vehiculo.Entity = value;
					if ((value != null))
					{
						value.Colaborador.Add(this);
						this._IdVehiculo = value.IdVehiculo;
					}
					else
					{
						this._IdVehiculo = default(Nullable<int>);
					}
					this.SendPropertyChanged("Vehiculo");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_ColaboradorEnvio(ColaboradorEnvio entity)
		{
			this.SendPropertyChanging();
			entity.Colaborador = this;
		}
		
		private void detach_ColaboradorEnvio(ColaboradorEnvio entity)
		{
			this.SendPropertyChanging();
			entity.Colaborador = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TEnvio")]
	public partial class Envio : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _IdEnvio;
		
		private int _IdCliente;
		
		private int _IdServicio;
		
		private System.DateTime _FechaEnvio;
		
		private System.DateTime _FechaRecojo;
		
		private decimal _Peso;
		
		private decimal _Volumen;
		
		private char _TipoDocumento;
		
		private decimal _TarifaBase;
		
		private System.Nullable<decimal> _MontoPago;
		
		private string _EstadoEnvio;
		
		private EntitySet<ColaboradorEnvio> _ColaboradorEnvio;
		
		private EntityRef<Cliente> _Cliente;
		
		private EntityRef<Servicio> _Servicio;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdEnvioChanging(int value);
    partial void OnIdEnvioChanged();
    partial void OnIdClienteChanging(int value);
    partial void OnIdClienteChanged();
    partial void OnIdServicioChanging(int value);
    partial void OnIdServicioChanged();
    partial void OnFechaEnvioChanging(System.DateTime value);
    partial void OnFechaEnvioChanged();
    partial void OnFechaRecojoChanging(System.DateTime value);
    partial void OnFechaRecojoChanged();
    partial void OnPesoChanging(decimal value);
    partial void OnPesoChanged();
    partial void OnVolumenChanging(decimal value);
    partial void OnVolumenChanged();
    partial void OnTipoDocumentoChanging(char value);
    partial void OnTipoDocumentoChanged();
    partial void OnTarifaBaseChanging(decimal value);
    partial void OnTarifaBaseChanged();
    partial void OnMontoPagoChanging(System.Nullable<decimal> value);
    partial void OnMontoPagoChanged();
    partial void OnEstadoEnvioChanging(string value);
    partial void OnEstadoEnvioChanged();
    #endregion
		
		public Envio()
		{
			this._ColaboradorEnvio = new EntitySet<ColaboradorEnvio>(new Action<ColaboradorEnvio>(this.attach_ColaboradorEnvio), new Action<ColaboradorEnvio>(this.detach_ColaboradorEnvio));
			this._Cliente = default(EntityRef<Cliente>);
			this._Servicio = default(EntityRef<Servicio>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdEnvio", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int IdEnvio
		{
			get
			{
				return this._IdEnvio;
			}
			set
			{
				if ((this._IdEnvio != value))
				{
					this.OnIdEnvioChanging(value);
					this.SendPropertyChanging();
					this._IdEnvio = value;
					this.SendPropertyChanged("IdEnvio");
					this.OnIdEnvioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdCliente", DbType="Int NOT NULL")]
		public int IdCliente
		{
			get
			{
				return this._IdCliente;
			}
			set
			{
				if ((this._IdCliente != value))
				{
					if (this._Cliente.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIdClienteChanging(value);
					this.SendPropertyChanging();
					this._IdCliente = value;
					this.SendPropertyChanged("IdCliente");
					this.OnIdClienteChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdServicio", DbType="Int NOT NULL")]
		public int IdServicio
		{
			get
			{
				return this._IdServicio;
			}
			set
			{
				if ((this._IdServicio != value))
				{
					if (this._Servicio.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIdServicioChanging(value);
					this.SendPropertyChanging();
					this._IdServicio = value;
					this.SendPropertyChanged("IdServicio");
					this.OnIdServicioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechaEnvio", DbType="Date NOT NULL")]
		public System.DateTime FechaEnvio
		{
			get
			{
				return this._FechaEnvio;
			}
			set
			{
				if ((this._FechaEnvio != value))
				{
					this.OnFechaEnvioChanging(value);
					this.SendPropertyChanging();
					this._FechaEnvio = value;
					this.SendPropertyChanged("FechaEnvio");
					this.OnFechaEnvioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechaRecojo", DbType="Date NOT NULL")]
		public System.DateTime FechaRecojo
		{
			get
			{
				return this._FechaRecojo;
			}
			set
			{
				if ((this._FechaRecojo != value))
				{
					this.OnFechaRecojoChanging(value);
					this.SendPropertyChanging();
					this._FechaRecojo = value;
					this.SendPropertyChanged("FechaRecojo");
					this.OnFechaRecojoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Peso", DbType="Decimal(10,2) NOT NULL")]
		public decimal Peso
		{
			get
			{
				return this._Peso;
			}
			set
			{
				if ((this._Peso != value))
				{
					this.OnPesoChanging(value);
					this.SendPropertyChanging();
					this._Peso = value;
					this.SendPropertyChanged("Peso");
					this.OnPesoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Volumen", DbType="Decimal(10,2) NOT NULL")]
		public decimal Volumen
		{
			get
			{
				return this._Volumen;
			}
			set
			{
				if ((this._Volumen != value))
				{
					this.OnVolumenChanging(value);
					this.SendPropertyChanging();
					this._Volumen = value;
					this.SendPropertyChanged("Volumen");
					this.OnVolumenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TipoDocumento", DbType="Char(1) NOT NULL")]
		public char TipoDocumento
		{
			get
			{
				return this._TipoDocumento;
			}
			set
			{
				if ((this._TipoDocumento != value))
				{
					this.OnTipoDocumentoChanging(value);
					this.SendPropertyChanging();
					this._TipoDocumento = value;
					this.SendPropertyChanged("TipoDocumento");
					this.OnTipoDocumentoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TarifaBase", DbType="Decimal(10,2) NOT NULL")]
		public decimal TarifaBase
		{
			get
			{
				return this._TarifaBase;
			}
			set
			{
				if ((this._TarifaBase != value))
				{
					this.OnTarifaBaseChanging(value);
					this.SendPropertyChanging();
					this._TarifaBase = value;
					this.SendPropertyChanged("TarifaBase");
					this.OnTarifaBaseChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MontoPago", AutoSync=AutoSync.Always, DbType="Decimal(14,3)", IsDbGenerated=true, UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<decimal> MontoPago
		{
			get
			{
				return this._MontoPago;
			}
			set
			{
				if ((this._MontoPago != value))
				{
					this.OnMontoPagoChanging(value);
					this.SendPropertyChanging();
					this._MontoPago = value;
					this.SendPropertyChanged("MontoPago");
					this.OnMontoPagoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EstadoEnvio", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string EstadoEnvio
		{
			get
			{
				return this._EstadoEnvio;
			}
			set
			{
				if ((this._EstadoEnvio != value))
				{
					this.OnEstadoEnvioChanging(value);
					this.SendPropertyChanging();
					this._EstadoEnvio = value;
					this.SendPropertyChanged("EstadoEnvio");
					this.OnEstadoEnvioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TEnvio_ColaboradorEnvio", Storage="_ColaboradorEnvio", ThisKey="IdEnvio", OtherKey="IdEnvio")]
		public EntitySet<ColaboradorEnvio> ColaboradorEnvio
		{
			get
			{
				return this._ColaboradorEnvio;
			}
			set
			{
				this._ColaboradorEnvio.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TCliente_TEnvio", Storage="_Cliente", ThisKey="IdCliente", OtherKey="IdCliente", IsForeignKey=true)]
		public Cliente Cliente
		{
			get
			{
				return this._Cliente.Entity;
			}
			set
			{
				Cliente previousValue = this._Cliente.Entity;
				if (((previousValue != value) 
							|| (this._Cliente.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Cliente.Entity = null;
						previousValue.Envio.Remove(this);
					}
					this._Cliente.Entity = value;
					if ((value != null))
					{
						value.Envio.Add(this);
						this._IdCliente = value.IdCliente;
					}
					else
					{
						this._IdCliente = default(int);
					}
					this.SendPropertyChanged("Cliente");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TServicio_TEnvio", Storage="_Servicio", ThisKey="IdServicio", OtherKey="IdServicio", IsForeignKey=true)]
		public Servicio Servicio
		{
			get
			{
				return this._Servicio.Entity;
			}
			set
			{
				Servicio previousValue = this._Servicio.Entity;
				if (((previousValue != value) 
							|| (this._Servicio.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Servicio.Entity = null;
						previousValue.Envio.Remove(this);
					}
					this._Servicio.Entity = value;
					if ((value != null))
					{
						value.Envio.Add(this);
						this._IdServicio = value.IdServicio;
					}
					else
					{
						this._IdServicio = default(int);
					}
					this.SendPropertyChanged("Servicio");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_ColaboradorEnvio(ColaboradorEnvio entity)
		{
			this.SendPropertyChanging();
			entity.Envio = this;
		}
		
		private void detach_ColaboradorEnvio(ColaboradorEnvio entity)
		{
			this.SendPropertyChanging();
			entity.Envio = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TServicio")]
	public partial class Servicio : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _IdServicio;
		
		private string _Descripcion;
		
		private decimal _TarifaBase;
		
		private EntitySet<CarritoCompras> _CarritoCompras;
		
		private EntitySet<Envio> _Envio;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdServicioChanging(int value);
    partial void OnIdServicioChanged();
    partial void OnDescripcionChanging(string value);
    partial void OnDescripcionChanged();
    partial void OnTarifaBaseChanging(decimal value);
    partial void OnTarifaBaseChanged();
    #endregion
		
		public Servicio()
		{
			this._CarritoCompras = new EntitySet<CarritoCompras>(new Action<CarritoCompras>(this.attach_CarritoCompras), new Action<CarritoCompras>(this.detach_CarritoCompras));
			this._Envio = new EntitySet<Envio>(new Action<Envio>(this.attach_Envio), new Action<Envio>(this.detach_Envio));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdServicio", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int IdServicio
		{
			get
			{
				return this._IdServicio;
			}
			set
			{
				if ((this._IdServicio != value))
				{
					this.OnIdServicioChanging(value);
					this.SendPropertyChanging();
					this._IdServicio = value;
					this.SendPropertyChanged("IdServicio");
					this.OnIdServicioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Descripcion", DbType="VarChar(200) NOT NULL", CanBeNull=false)]
		public string Descripcion
		{
			get
			{
				return this._Descripcion;
			}
			set
			{
				if ((this._Descripcion != value))
				{
					this.OnDescripcionChanging(value);
					this.SendPropertyChanging();
					this._Descripcion = value;
					this.SendPropertyChanged("Descripcion");
					this.OnDescripcionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TarifaBase", DbType="Decimal(10,2) NOT NULL")]
		public decimal TarifaBase
		{
			get
			{
				return this._TarifaBase;
			}
			set
			{
				if ((this._TarifaBase != value))
				{
					this.OnTarifaBaseChanging(value);
					this.SendPropertyChanging();
					this._TarifaBase = value;
					this.SendPropertyChanged("TarifaBase");
					this.OnTarifaBaseChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TServicio_CarritoCompras", Storage="_CarritoCompras", ThisKey="IdServicio", OtherKey="IdServicio")]
		public EntitySet<CarritoCompras> CarritoCompras
		{
			get
			{
				return this._CarritoCompras;
			}
			set
			{
				this._CarritoCompras.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TServicio_TEnvio", Storage="_Envio", ThisKey="IdServicio", OtherKey="IdServicio")]
		public EntitySet<Envio> Envio
		{
			get
			{
				return this._Envio;
			}
			set
			{
				this._Envio.Assign(value);
			}
		}

        public int Cantidad { get; internal set; }

        public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_CarritoCompras(CarritoCompras entity)
		{
			this.SendPropertyChanging();
			entity.Servicio = this;
		}
		
		private void detach_CarritoCompras(CarritoCompras entity)
		{
			this.SendPropertyChanging();
			entity.Servicio = null;
		}
		
		private void attach_Envio(Envio entity)
		{
			this.SendPropertyChanging();
			entity.Servicio = this;
		}
		
		private void detach_Envio(Envio entity)
		{
			this.SendPropertyChanging();
			entity.Servicio = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TUsuario")]
	public partial class Usuario : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _CodUsuario;
		
		private System.Data.Linq.Binary _Contrasena;
		
		private EntitySet<Cliente> _Cliente;
		
		private EntitySet<Colaborador> _Colaborador;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCodUsuarioChanging(string value);
    partial void OnCodUsuarioChanged();
    partial void OnContrasenaChanging(System.Data.Linq.Binary value);
    partial void OnContrasenaChanged();
    #endregion
		
		public Usuario()
		{
			this._Cliente = new EntitySet<Cliente>(new Action<Cliente>(this.attach_Cliente), new Action<Cliente>(this.detach_Cliente));
			this._Colaborador = new EntitySet<Colaborador>(new Action<Colaborador>(this.attach_Colaborador), new Action<Colaborador>(this.detach_Colaborador));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CodUsuario", DbType="VarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string CodUsuario
		{
			get
			{
				return this._CodUsuario;
			}
			set
			{
				if ((this._CodUsuario != value))
				{
					this.OnCodUsuarioChanging(value);
					this.SendPropertyChanging();
					this._CodUsuario = value;
					this.SendPropertyChanged("CodUsuario");
					this.OnCodUsuarioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Contrasena", DbType="VarBinary(8000) NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public System.Data.Linq.Binary Contrasena
		{
			get
			{
				return this._Contrasena;
			}
			set
			{
				if ((this._Contrasena != value))
				{
					this.OnContrasenaChanging(value);
					this.SendPropertyChanging();
					this._Contrasena = value;
					this.SendPropertyChanged("Contrasena");
					this.OnContrasenaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TUsuario_TCliente", Storage="_Cliente", ThisKey="CodUsuario", OtherKey="CodUsuario")]
		public EntitySet<Cliente> Cliente
		{
			get
			{
				return this._Cliente;
			}
			set
			{
				this._Cliente.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TUsuario_TColaborador", Storage="_Colaborador", ThisKey="CodUsuario", OtherKey="CodUsuario")]
		public EntitySet<Colaborador> Colaborador
		{
			get
			{
				return this._Colaborador;
			}
			set
			{
				this._Colaborador.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Cliente(Cliente entity)
		{
			this.SendPropertyChanging();
			entity.Usuario = this;
		}
		
		private void detach_Cliente(Cliente entity)
		{
			this.SendPropertyChanging();
			entity.Usuario = null;
		}
		
		private void attach_Colaborador(Colaborador entity)
		{
			this.SendPropertyChanging();
			entity.Usuario = this;
		}
		
		private void detach_Colaborador(Colaborador entity)
		{
			this.SendPropertyChanging();
			entity.Usuario = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TVehiculo")]
	public partial class Vehiculo : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _IdVehiculo;
		
		private string _Marca;
		
		private string _Modelo;
		
		private string _Placa;
		
		private decimal _CapacidadCarga;
		
		private EntitySet<Colaborador> _Colaborador;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdVehiculoChanging(int value);
    partial void OnIdVehiculoChanged();
    partial void OnMarcaChanging(string value);
    partial void OnMarcaChanged();
    partial void OnModeloChanging(string value);
    partial void OnModeloChanged();
    partial void OnPlacaChanging(string value);
    partial void OnPlacaChanged();
    partial void OnCapacidadCargaChanging(decimal value);
    partial void OnCapacidadCargaChanged();
    #endregion
		
		public Vehiculo()
		{
			this._Colaborador = new EntitySet<Colaborador>(new Action<Colaborador>(this.attach_Colaborador), new Action<Colaborador>(this.detach_Colaborador));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdVehiculo", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int IdVehiculo
		{
			get
			{
				return this._IdVehiculo;
			}
			set
			{
				if ((this._IdVehiculo != value))
				{
					this.OnIdVehiculoChanging(value);
					this.SendPropertyChanging();
					this._IdVehiculo = value;
					this.SendPropertyChanged("IdVehiculo");
					this.OnIdVehiculoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Marca", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string Marca
		{
			get
			{
				return this._Marca;
			}
			set
			{
				if ((this._Marca != value))
				{
					this.OnMarcaChanging(value);
					this.SendPropertyChanging();
					this._Marca = value;
					this.SendPropertyChanged("Marca");
					this.OnMarcaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Modelo", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string Modelo
		{
			get
			{
				return this._Modelo;
			}
			set
			{
				if ((this._Modelo != value))
				{
					this.OnModeloChanging(value);
					this.SendPropertyChanging();
					this._Modelo = value;
					this.SendPropertyChanged("Modelo");
					this.OnModeloChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Placa", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string Placa
		{
			get
			{
				return this._Placa;
			}
			set
			{
				if ((this._Placa != value))
				{
					this.OnPlacaChanging(value);
					this.SendPropertyChanging();
					this._Placa = value;
					this.SendPropertyChanged("Placa");
					this.OnPlacaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CapacidadCarga", DbType="Decimal(10,2) NOT NULL")]
		public decimal CapacidadCarga
		{
			get
			{
				return this._CapacidadCarga;
			}
			set
			{
				if ((this._CapacidadCarga != value))
				{
					this.OnCapacidadCargaChanging(value);
					this.SendPropertyChanging();
					this._CapacidadCarga = value;
					this.SendPropertyChanged("CapacidadCarga");
					this.OnCapacidadCargaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TVehiculo_TColaborador", Storage="_Colaborador", ThisKey="IdVehiculo", OtherKey="IdVehiculo")]
		public EntitySet<Colaborador> Colaborador
		{
			get
			{
				return this._Colaborador;
			}
			set
			{
				this._Colaborador.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Colaborador(Colaborador entity)
		{
			this.SendPropertyChanging();
			entity.Vehiculo = this;
		}
		
		private void detach_Colaborador(Colaborador entity)
		{
			this.SendPropertyChanging();
			entity.Vehiculo = null;
		}
	}
}
#pragma warning restore 1591
